---
title: "Bsub transcriptomics"
author: "Yen-Kai Chen"
date: "01/05/2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Set up transcriptomic data
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/lipidomics")
file_url <- "https://genelab-data.ndc.nasa.gov/genelab/static/media/dataset/GLDS-138_rna_seq_Normalized_Counts.csv?version=1"
GLDS138RNA = 'GLDS-138_rna_seq_Normalized_Counts.csv'
download.file(file_url, GLDS138RNA)
edata <- read.csv(GLDS138RNA, stringsAsFactors = FALSE)

dim(edata)
rowName <- edata[,1]
rownames(edata) <- rowName
edata <- edata[,-1]
colnames(edata) <- substr(colnames(edata),start=16,stop=23)
edata <- as.data.frame(edata)
edata <- t(edata)

etreat <- data.frame(c(rep("Flight", 9), rep("Ground Control", 9)))
colnames(etreat) <- c("Treatment")
edat <- as.data.frame(edata)
edat[,"Treatment"] <- etreat
edat <- edat[,c("Treatment", setdiff(names(edat), "Treatment"))]
```
# PCA

```{r}
library(mixOmics)
X <- edat[,-1]
MyResult.pca <- pca(X, ncomp = 3, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), title = 'B. subtilis Transcriptome: PCA',
          group = edat$Treatment, legend.title = 'Treatment', legend = TRUE,
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotIndiv(MyResult.pca, comp = c(1,2,3), title = 'B. subtilis Transcriptome: PCA',
          group = edat$Treatment, legend.title = 'Treatment', legend = TRUE,
          ellipse = TRUE, style = "3d", ind.names = FALSE)
plotVar(MyResult.pca, cutoff = 0.941)
MyResult.pca 
```

# IPCA
```{r}
# Pellet - Flight vs Ground
X <- edat[,-1]
MyResult.ipca <- ipca(X, ncomp = 4, mode="deflation")
plotIndiv(MyResult.ipca, comp = c(1,2), legend = TRUE, title = 'B. subtilis Transcriptome: IPCA',
          group = edat$Treatment, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotIndiv(MyResult.ipca, comp = c(1,2,3), legend = TRUE, title = 'B. subtilis Transcriptome: IPCA',
          group = edat$Treatment, legend.title = 'Treatment',
          ellipse = TRUE, style = "3d", ind.names = FALSE)
plotVar(MyResult.ipca, cutoff = 0.8)
MyResult.ipca$kurtosis # first two components
hist(MyResult.ipca$loadings$X[,1], main = "Histogram of IPC1's loadings", xlab = "IPC1 Loadings")
hist(MyResult.ipca$loadings$X[,2], main = "Histogram of IPC2's loadings", xlab = "IPC2 Loadings")
hist(MyResult.ipca$loadings$X[,3], main = "Histogram of IPC3's loadings", xlab = "IPC3 Loadings")
hist(MyResult.ipca$loadings$X[,4], main = "Histogram of IPC4's loadings", xlab = "IPC4 Loadings")
```



















```{r}
devtools::session_info()
```