---
title: "BSub reanalysis July 2020"
author: "Yen-Kai Chen"
date: "03/07/2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up
```{r}
# set workingspace - if required
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics")

# download
file_url <- "https://genelab-data.ndc.nasa.gov/genelab/static/media/dataset/GLDS-138_metabolomics_mx%20367428_NASA_bacteria%20cells_09-2017_submit%20.csv?version=1"
BRIC23metab = 'GLDS-138_metabolomics_mx 367428_NASA_bacteria cells_09-2017_submit.csv'
download.file(file_url, BRIC23metab)
Bdata <- read.csv(BRIC23metab, stringsAsFactors = FALSE)

# if already downloaded
Bdata <- read.csv("GLDS-138_metabolomics_mx 367428_NASA_bacteria cells_09-2017_submit.csv", stringsAsFactors = FALSE)

# filter
Bdata <- t(Bdata)
Bdata <- Bdata[-c(2:7, 114:118),]
Bdata <- Bdata[,-c(1:2,6:8)]
Bdata[1,1:3] <- Bdata[2,1:3]
Bdata <- Bdata[-c(2),]

# Column and row names
columnName <- Bdata[1,]
rowName    <- Bdata[,1]
colnames(Bdata) <- columnName
rownames(Bdata) <- rowName
Bdata <- Bdata[-1,]
Bdata <- Bdata[,-1]
Bdata <- as.data.frame(Bdata)

# as.numeric
Bdata[,3:ncol(Bdata)] <- lapply(Bdata[,3:ncol(Bdata)], function(x) as.numeric(as.character(x)))

```

# data transformation
```{r}
# Row-wise correction
BdataRWC <- as.data.frame(Bdata)
rowi <- BdataRWC[,3:ncol(BdataRWC)]

BdataRWC[,3:ncol(BdataRWC)] <- rowi / rowSums(rowi) # by the peak of all sums

sum(BdataRWC[105,3:ncol(BdataRWC)]) # checking the row wise correction worked well

# Baseline correction
tail(BdataRWC[,1:5], 1)

blc <- tail(BdataRWC,1)
tail(blc[,1:5],1)
BdataBLC <- BdataRWC[-nrow(BdataRWC),]

BdataBLC[,3:ncol(BdataBLC)] <- BdataBLC[,3:ncol(BdataBLC)] - blc[rep(1,104),3:ncol(blc)]
BdataRWC1[1,3] - blc[,3] # check that the values are correct

# setup for normalisation
autoscale <- function(a){
  colmean <- apply(a,2,mean) # column mean
  colsd <- apply(a, 2, sd) # col standard deviation
  cv <- sweep(a, 2, colmean, "-") # minus mean center
  cv <- sweep(cv, 2, colsd, "/") # divide by sd
  return(cv)
}

rangescale <- function(r) {
  apply(r, 2, function(x) (x  - mean(x))/(max(x) - min(x)))
}

paretoscale <- function(p){
  colmean <- apply(p,2,mean) 
  colsd <- apply(p, 2, sd) 
  colsqrtsd <- sqrt(colsd)
  cv <- sweep(p, 2, colmean, "-") 
  cv <- sweep(cv, 2, colsqrtsd, "/") 
  return(cv)
}

levelscale <- function(l){
  colmean <- apply(l,2,mean)
  cv <- sweep(l, 2, colmean, "-")
  cv <- sweep(cv, 2, colmean, "/")
  return(cv)
}

centrescale <- function(c){
  colmean <- apply(c,2,mean)
  cv <- sweep(c, 2, colmean, "-")
  return(cv)
}

Bsub.pn <- BdataBLC[1:52,] # B.subtilis pre-normalisation
Bsub.pn <- Bsub.pn[,-2]
Bsub.pn$comment <- gsub("B. subtilis ", "", Bsub.pn$comment)

Bsub.log <- Bsub.pn; Bsub.log[,2:ncol(Bsub.log)] <- log(Bsub.pn[,2:ncol(Bsub.pn)]+1)
Bsub.as <- Bsub.pn; Bsub.as[,2:ncol(Bsub.as)] <- autoscale(Bsub.pn[,2:ncol(Bsub.pn)])
Bsub.r <- Bsub.pn; Bsub.r[,2:ncol(Bsub.r)] <- rangescale(Bsub.pn[,2:ncol(Bsub.pn)])
Bsub.par <- Bsub.pn; Bsub.par[,2:ncol(Bsub.par)] <- paretoscale(Bsub.pn[,2:ncol(Bsub.pn)])
Bsub.lvl <- Bsub.pn; Bsub.lvl[,2:ncol(Bsub.lvl)] <- levelscale(Bsub.pn[,2:ncol(Bsub.pn)])
Bsub.c <- Bsub.pn; Bsub.c[,2:ncol(Bsub.c)] <- centrescale(Bsub.pn[,2:ncol(Bsub.pn)])

boxplot(Bsub.pn[,2:ncol(Bsub.pn)], col = 2, range = 0, las = 2)
boxplot(Bsub.log[,2:ncol(Bsub.log)], col = 2, range = 0, las = 2)
boxplot(Bsub.as[,2:ncol(Bsub.as)], col = 3, range = 0, las = 2)
boxplot(Bsub.r[,2:ncol(Bsub.r)], col = 3, range = 0, las = 2)
boxplot(Bsub.par[,2:ncol(Bsub.par)], col = 3, range = 0, las = 2)
boxplot(Bsub.lvl[,2:ncol(Bsub.lvl)], col = 3, range = 0, las = 2)
boxplot(Bsub.c[,2:ncol(Bsub.c)], col = 3, range = 0, las = 2)

# autoscale file if required
write.csv(Bsub.as,"Bsub.as.csv", row.names = F)

Bsub.as <- read.csv("Bsub.as.csv", stringsAsFactors = FALSE)
```

# PCA/IPCA
```{r}
library(mixOmics)

# Get rid of Control ASAP and Frozen - so just media and pellet
BsubMP <- Bsub.as[-c(1:8, 27:34),]
# BsubMP$Label <- factor(BsubMP$Label)

# Just Pellet - the bacteria - comparison of just flight vs ground
BsubFG <- BsubMP[c(19:36),]
BsubFG$comment <- gsub("Pellet ", "", BsubFG$comment)

# Just Media consumed by the bacteria - F vs G
BsubMd <- BsubMP[c(1:18),]
BsubMd$comment <- gsub("Media ", "", BsubMd$comment)

# the general file
X <- Bsub.as[,2:ncol(Bsub.as)]
MyResult.ipca <- ipca(X, ncomp = 3, mode ="deflation")
MyResult.ipca$kurtosis # proceed with PCA
MyResult.pca <- pca(X, ncomp = 3, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), title = 'Spaceflight: B. subtilis PCA',
          legend = TRUE, group = Bsub.as$comment, legend.title = 'Treatment',
          ind.names = FALSE)

# # Pellet - Flight vs Ground
X <- BsubFG[,2:ncol(BsubFG)]
MyResult.ipca <- ipca(X, ncomp = 3, mode ="deflation")
MyResult.ipca$kurtosis # proceed with PCA
MyResult.pca <- pca(X, ncomp = 3, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), title = 'B. subtilis - Flight vs Ground: PCA',
          legend = TRUE, group = BsubFG$comment, legend.title = 'Treatment',
          ind.names = FALSE)

```
















