---
title: "Bsub without unknown"
author: "Yen-Kai Chen"
date: "14/05/2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set up
GLDS138.as <- read.csv("GLDS138.as.csv", check.names = FALSE, header = TRUE)
utils::View(GLDS138.as)

## remove unknown metabolites
GLDS138 <- GLDS138.as[,1:151]

# Just B. subtilis
Bsub.as <- GLDS138[c(1:52),]
Bsub.as <- Bsub.as[,-3]

# Get rid of Control ASAP and Frozen - so just media and pellet
BsubMP <- Bsub.as[-c(1:8, 27:34),]
BsubMP$Label <- factor(BsubMP$Label)

# Just Pellet - the bacteria - comparison of just flight vs ground
BsubFG <- BsubMP[c(19:36),]
BsubFG$Label <- gsub("Pellet ", "", BsubFG$Label)
# write.csv(BsubFG,"GLDS138.BsubFG.as.csv", row.names = F) # used later for metaboanalyst

# Just Media consumed by the bacteria - F vs G
BsubMd <- BsubMP[c(1:18),]
BsubMd$Label <- gsub("Media ", "", BsubMd$Label)
```
# IPCA/PCA
```{r}
library(mixOmics)
X <- GLDS138[,4:ncol(GLDS138)]
MyResult.ipca$kurtosis # proceed with PCA
MyResult.pca <- pca(X, ncomp = 3, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), legend = TRUE, title = 'GLDS138: PCA',
          group = GLDS138.as$Label, legend.title = 'Treatment',
          ellipse = FALSE, style = "ggplot2", ind.names = FALSE, 
          pch = GLDS138.as$species, legend.title.pch = 'Species')
plotVar(MyResult.pca, cutoff = 0.8)


# B subtilis
X <- Bsub.as[,3:ncol(Bsub.as)]
MyResult.ipca <- ipca(X, ncomp = 3, mode="deflation")
MyResult.ipca$kurtosis 
MyResult.pca <- pca(X, ncomp = 3, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), legend = TRUE, title = 'B. subtilis: PCA',
          group = Bsub.as$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.pca, cutoff = 0.8)
MyResult.pca

# Media and pellet
X <- BsubMP[,3:ncol(BsubMP)]
MyResult.ipca <- ipca(X, ncomp = 3, mode="deflation")
MyResult.ipca$kurtosis 
plotIndiv(MyResult.ipca, comp = c(1,2), legend = TRUE, title = 'B. subtilis - Media vs Pellet: IPCA',
          group = BsubMP$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.ipca, cutoff = 0.8)

# Pellet - Flight vs Ground
X <- BsubFG[,3:ncol(BsubFG)]
MyResult.ipca <- ipca(X, ncomp = 4, mode="deflation")
MyResult.ipca$kurtosis 
plotIndiv(MyResult.ipca, comp = c(1,2), legend = TRUE, title = 'B. subtilis - Flight vs Ground: IPCA',
          group = BsubFG$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotIndiv(MyResult.ipca, comp = c(1,2,3), legend = TRUE, title = 'B. subtilis - Flight vs Ground: IPCA',
          group = BsubFG$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "3d", ind.names = FALSE)
plotVar(MyResult.ipca, cutoff = 0.675)
MyResult.ipca$kurtosis # first two components
hist(MyResult.ipca$loadings$X[,1], main = "Histogram of IPC1's loadings", xlab = "IPC1 Loadings")
hist(MyResult.ipca$loadings$X[,2], main = "Histogram of IPC2's loadings", xlab = "IPC2 Loadings")
hist(MyResult.ipca$loadings$X[,3], main = "Histogram of IPC3's loadings", xlab = "IPC3 Loadings")

# Media - Flight vs Ground
X <- BsubMd[,3:ncol(BsubMd)]
MyResult.ipca <- ipca(X, ncomp = 3, mode="deflation")
MyResult.ipca$kurtosis 
plotIndiv(MyResult.ipca, comp = c(1,2), legend = TRUE, 
          title = 'B. subtilis consumed media - Flight vs Ground: IPCA',
          group = BsubMd$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.ipca, cutoff = 0.8)

```
# top IPCA metabolites
```{r}
top_10_metab <- names(sort(abs(MyResult.pca$rotation[,1]), decreasing = TRUE)[1:10])
MyResult.pca$rotation[top_10_metab,1]

# top metabolites for PC2
top_10_metab <- names(sort(abs(MyResult.pca$rotation[,2]), decreasing = TRUE)[1:10])
MyResult.pca$rotation[top_10_metab,2]

# top metabolites for PC3
top_10_metab <- names(sort(abs(MyResult.pca$rotation[,3]), decreasing = TRUE)[1:10])
MyResult.pca$rotation[top_10_metab,3]

# anova
anova_data <- BsubFG[,c("Label", "glycerol-3-galactoside", "dihydroxyacetone", "orotic acid", "uracil", "serine", "n-acetyl-d-hexosamine")]
library(tidyverse)
anova_data %>% pivot_longer(-Label, names_to = "Metabolite", values_to = "value") %>%
  mutate(Metabolite = factor(Metabolite, levels = c("glycerol-3-galactoside", "dihydroxyacetone", "orotic acid", "uracil", "serine", "n-acetyl-d-hexosamine"))) %>%
  ggplot(aes(x = Label, y = value, color = Metabolite)) +
  geom_boxplot() +
  facet_wrap(~Metabolite)
```
#Partial Least Squares - Discriminant Analysis
```{r}
# set up
X <- BsubFG[,-c(1:2)]
Y <- BsubFG$Label
summary(Y)
dim(X)
length(Y)

##  Tuning parameters and numerical outputs
# check the best number of components to use 
MyResult.splsda2 <- plsda(X, Y, ncomp = 5)
MyPerf.plsda <- perf(MyResult.splsda2, validation = "Mfold", folds = 3,
                     progressBar = FALSE, nrepeat = 50)
plot(MyPerf.plsda, col = color.mixo(5:7), sd = TRUE, legend.position = "horizontal") # looks to be 2 components

list.keepX <- c(1:10,  seq(20, 100, 10))
list.keepX # output the grid of values tested

tune.splsda.srbct <- tune.splsda(X, Y, ncomp = 2, 
                                 validation = 'Mfold',
                                 folds = 3, dist = 'max.dist', progressBar = FALSE,
                                 measure = "BER", test.keepX = list.keepX,
                                 nrepeat = 50)
error <- tune.splsda.srbct$error.rate
ncomp <- tune.splsda.srbct$choice.ncomp$ncomp # optimal number of components based on t-tests on the error rate
ncomp # confirmed to be 1.
# check the number of metabolites to keep per component
select.keepX <- tune.splsda.srbct$choice.keepX[1:ncomp]  # optimal number of variables to select
select.keepX 
select.keepX <- tune.splsda.srbct$choice.keepX[1:2]  # optimal no of variables for 2 components
select.keepX

plot(tune.splsda.srbct, col = color.jet(2))

# The final graph - we have to use two component 
MyResult.splsda.final <- splsda(X, Y, ncomp = 2, keepX = select.keepX)
plotIndiv(MyResult.splsda.final, ind.names = FALSE, legend=TRUE,
          ellipse = TRUE, title="sPLS-DA - final result")

plotLoadings(MyResult.splsda.final, comp = 1, title = 'Loadings on comp 1', 
             contrib = 'max', method = 'mean') # only ribonic acid left
X11()
cim(MyResult.splsda.final, comp = 1, title = "Component 1")
plotArrow(MyResult.splsda.final, legend=T)

# Background prediction
background <- background.predict(MyResult.splsda.final, comp.predicted = 2,
                                 dist = "max.dist")
plotIndiv(MyResult.splsda.final, comp = 1:2, group = BsubFG$Label,
          ind.names = FALSE, title = "Maximum distance",
          legend = TRUE,  background = background)


# take a look at the boxplot anyway
splsda_metab <- BsubFG[,c("Label", "ribonic acid")]
library(tidyverse)
splsda_metab %>% pivot_longer(-Label, names_to = "Metabolite", values_to = "value") %>%
  mutate(Metabolite = factor(Metabolite, levels = c("ribonic acid"))) %>%
  ggplot(aes(x = Label, y = value, color = Metabolite)) +
  geom_boxplot() +
  facet_wrap(~Metabolite)
```













```{r}
devtools::session_info()
```