---
title: "GLDS-138 Metabolomics - S. Aureus"
author: "Yen-Kai Chen"
date: "07/04/2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load libraries
rm(list = ls())
library(ggplot2)
library(RColorBrewer)
library(gplots)
library(ggbiplot)
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics")

# Same dataset as B. subtilis, so no download require
Bdata <- read.csv("GLDS-138_metabolomics_mx 367428_NASA_bacteria cells_09-2017_submit.csv", stringsAsFactors = FALSE)

# filtering data
Bdata <- t(Bdata)
Bdata <- Bdata[-c(2:7, 114:118),]
Bdata <- Bdata[,-c(1:2,6:8)]
Bdata[1,1:3] <- Bdata[2,1:3]
Bdata <- Bdata[-c(2),]

# Giving column and row names
columnName <- Bdata[1,]
rowName    <- Bdata[,1]
colnames(Bdata) <- columnName
rownames(Bdata) <- rowName
Bdata <- Bdata[-1,]
Bdata <- Bdata[,-1]
Bdata <- as.data.frame(Bdata)

# as.numeric
Bdata[,3:ncol(Bdata)] <- lapply(Bdata[,3:ncol(Bdata)], function(x) as.numeric(as.character(x)))
```
```{r}
# Row-wise correction
BdataRWC <- as.data.frame(Bdata)
rowi <- BdataRWC[,3:ncol(BdataRWC)]

BdataRWC[,3:ncol(BdataRWC)] <- rowi / rowSums(rowi) # by the peak of all sums

sum(BdataRWC[105,3:ncol(BdataRWC)]) # checking the row wise correction worked well

# Baseline correction
blc <- tail(BdataRWC,1)
tail(blc[,1:5],1)
BdataRWC1 <- BdataRWC[-nrow(BdataRWC),]
BdataBLC <- BdataRWC1 # creating an intermediate step so no rows are accidentally deleted

BdataBLC[,3:ncol(BdataBLC)] <- BdataBLC[,3:ncol(BdataBLC)] - blc[rep(1,104),3:ncol(blc)]

# xylose <- BdataRWC1[1,3] - blc[,3] # double check that the values are correct
# mb39 <- BdataRWC1[104,715] - blc[,715]

utils::View(BdataBLC)

# separating B. subtilis and S. aureus dataset
Saur.prenorm <- BdataBLC[53:104,]   # S. aureus  pre-normalisation
Saur.prenorm <- Saur.prenorm[,-2]
Saur.prenorm$comment <- gsub("S. aureus", "", Saur.prenorm$comment)
Saur.prenorm$comment <- gsub("S. Aureus", "", Saur.prenorm$comment)

# setting up the scales for normalisation

autoscale <- function(a){
  colmean <- apply(a,2,mean) # column mean
  colsd <- apply(a, 2, sd) # col standard deviation
  cv <- sweep(a, 2, colmean, "-") # minus mean center
  cv <- sweep(cv, 2, colsd, "/") # divide by sd
  return(cv)
}

# normalise by autoscale
Saur.autoscale <- Saur.prenorm
Saur.autoscale[,2:ncol(Saur.autoscale)] <- autoscale(Saur.prenorm[,2:ncol(Saur.prenorm)])

```
# check on normalisation
```{r}
boxplot(Saur.prenorm[,2:ncol(Saur.prenorm[1:200])], col = 2, range = 0, las =2)
boxplot(log2(Saur.prenorm[,2:ncol(Saur.prenorm[1:200])]+1), col = 2, range = 0)
boxplot(Saur.autoscale[,2:ncol(Saur.autoscale[1:200])], col =2, range = 0, las = 2)

plot(density(Saur.prenorm[,2]),col=2)
lines(density(Saur.prenorm[,3]),col=3)

plot(density(Saur.autoscale[,2]),col=2) # density-plot
lines(density(Saur.autoscale[,3]),col=3)
```
# Conduct PCA 
```{r}
# set up
SaurPCA.autoscale <- Saur.autoscale[,-1]
SaurPCA.autoscale <- as.data.frame(SaurPCA.autoscale)

# PCA
pca <- prcomp(SaurPCA.autoscale)
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
barplot(pca.var.per, main = "Scree Plot", xlab="Principal Component", ylab="Percent Variation")
pca.data <- data.frame(Sample=rownames(pca$x),
                       X=pca$x[,1],
                       Y=pca$x[,2])
pcaplot <- ggplot(data=pca.data, aes(x=X, y=Y, label=Sample)) +
  geom_text(aes(color=Saur.autoscale$comment)) +
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) +
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) +
  theme_bw() +
  ggtitle("S.aureus PCA Graph")
pcaplot
```
Difficult to discern difference between Media Positive Ctrl ASAP and Frozen, and Pellet Positive Ctrl ASAP and Frozen separately.
Problem is that Media Positive FROZEN does not have the expression as Ground Control, meaning potential batch effects.

# Fewer variables
```{r}
# Break up into fewer variables
Saur.as <- Saur.autoscale[-c(19:26, 45:52),]
SaurPCA.as <- Saur.as[,-1]
SaurPCA.as <- as.data.frame(SaurPCA.as)

# PCA
pca <- prcomp(SaurPCA.as, retx = TRUE, center = FALSE, scale = FALSE)
pcaresults <- summary(pca)
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
barplot(pca.var.per, main = "Scree Plot", xlab="Principal Component", ylab="Percent Variation")

SAscree.data <- as.data.frame(pcaresults$importance) # same as summary(pca)
SAscore.data <- as.data.frame(pcaresults$x)
SAloadings.data <- as.data.frame(pcaresults$rotation)

PC123 <- SAscore.data[,c(1:4)]

Group <- Saur.as$comment
PC123$Group <- cbind(Group)

ggplot(PC123, aes(PC1, PC2)) +
  geom_point(aes(shape=Group, color = Group)) +
  geom_text(aes(label=abbreviate(Group), color = Group)) +
  stat_ellipse(aes(colour = Group)) + 
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) +
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) + 
  ggtitle("S. aureus PCA Scores Plot")

ggplot(PC123, aes(PC2, PC3)) +
  geom_point(aes(shape=Group, color = Group)) +
  geom_text(aes(label=abbreviate(Group), color = Group)) +
  stat_ellipse(aes(colour = Group)) + 
  xlab(paste("PC2 - ", pca.var.per[2], "%", sep="")) +
  ylab(paste("PC3 - ", pca.var.per[3], "%", sep="")) + 
  ggtitle("S. aureus PCA Scores Plot")
```

# Look at top metabolites
```{r}
loading_scores <- pca$rotation[,1]
metab_scores <- abs(loading_scores)
metab_score_ranked <- sort(metab_scores, decreasing = TRUE)
top_10_metab <- names(metab_score_ranked[1:10])
top_10_metab
pca$rotation[top_10_metab,1]

# analyse top metabolties
m1 <- ggplot(SaurPCA.as, aes(x=.data[["102304"]], y=Saur.as$comment)) +
  geom_boxplot() +
  geom_jitter()
m1

qplot(.data[["102304"]], .data[["130478"]], data = SaurPCA.as, colour = Saur.as$comment)

# plot PC1 loadings versus metabolite
as.pca <- prcomp(SaurPCA.as)

PCs.mat <-  round(as.pca$rotation[,1:3], digits = 5)
pc1_loadings.df <- data.frame(Metabolite = row.names(PCs.mat), PCs.mat)

ggplot(pc1_loadings.df, aes(y = PC1, x = reorder(Metabolite, -PC1))) +
  geom_point(size = 3) +
  geom_hline(yintercept = 0, colour = "red",
             linetype = "dashed", size =1) +
  xlab("Metabolite") +
  theme_bw() +
  theme(axis.text = element_text(size = 18),
        axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title = element_text(size = 30))


```













