---
title: "MetaboAnalyst"
author: "Yen-Kai Chen"
date: "09/04/2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Initial set up
```{r}
# Load libraries
rm(list = ls())
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics")

# Same dataset as B. subtilis, so no download require
Bdata <- read.csv("GLDS-138_metabolomics_mx 367428_NASA_bacteria cells_09-2017_submit.csv", stringsAsFactors = FALSE)

# filtering data for MetaboAnalyst (Samples in rows (unpaired))
Bdata <- t(Bdata)
Bdata <- Bdata[-c(2:7, 114:118),]
Bdata <- Bdata[,-c(1:2,6:8)]
Bdata[1,1:3] <- Bdata[2,1:3]
Bdata <- Bdata[-c(2),]

rownames(Bdata) <- NULL

Bdata[1,1] <- "Sample"   # renaming to suit MetaboAnalyst
Bdata[1,2] <- "Label"

# Giving column and row names
columnName <- Bdata[1,]
colnames(Bdata) <- columnName
Bdata <- Bdata[-1,]
Bdata <- as.data.frame(Bdata)

# as.numeric
Bdata[,4:ncol(Bdata)] <- lapply(Bdata[,4:ncol(Bdata)], function(x) as.numeric(as.character(x)))
```
```{r}
# Row-wise correction
BdataRWC <- as.data.frame(Bdata)
rowi <- BdataRWC[,4:ncol(BdataRWC)]

BdataRWC[,4:ncol(BdataRWC)] <- rowi / rowSums(rowi) # by the peak of all sums

sum(BdataRWC[105,4:ncol(BdataRWC)]) # checking the row wise correction worked well

# Baseline correction
tail(BdataRWC[,1:5], 1)

blc <- tail(BdataRWC,1)
tail(blc[,1:5],1)
BdataRWC1 <- BdataRWC[-nrow(BdataRWC),]
BdataBLC <- BdataRWC1 # creating an intermediate step so no rows are accidentally deleted

BdataBLC[,4:ncol(BdataBLC)] <- BdataBLC[,4:ncol(BdataBLC)] - blc[rep(1,104),4:ncol(blc)]

# xylose <- BdataRWC1[1,4] - blc[,4] # double check that the values are correct
# mb39 <- BdataRWC1[104,715] - blc[,715]

utils::View(BdataBLC)

# separating B. subtilis and S. aureus dataset
Bsub.data <- BdataBLC[1:52,]     # B.subtilis pre-normalisation
Bsub.data <- Bsub.data[,-3]
Bsub.data$Label <- gsub("B. subtilis", "", Bsub.data$Label)
Saur.data <- BdataBLC[53:104,]   # S. aureus  pre-normalisation
rownames(Saur.data) <- NULL
Saur.data <- Saur.data[,-3]
Saur.data$Label <- gsub("S. aureus", "", Saur.data$Label)
Saur.data$Label <- gsub("S. Aureus", "", Saur.data$Label)
```
# Create csv for MetaboAnalyst
```{r}
write.csv(Bsub.data,"GLDS138.Bsub.csv", row.names = F)
write.csv(Saur.data,"GLDS138.Saur.csv", row.names = F)

library(MetaboAnalystR)
```
# B. subtilis - Statistical analysis
```{r}
# set up
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "GLDS138.Bsub.csv", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "NULL", "NULL", "AutoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)

# Anova
mSet<-ANOVA.Anal(mSet, F, 1.0E-20, "fisher", FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 1.0E-20, "tukey", FALSE)
mSet<-PlotANOVA(mSet, "aov_10_", "png", 72, width=NA)

# Correlation analysis
mSet<-Match.Pattern(mSet, "pearson", "1-2-3-4-5-6-7-8")
mSet<-PlotCorr(mSet, "ptn_9_", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "8-7-6-5-4-3-2-1")
mSet<-PlotCorr(mSet, "ptn_10_", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "1-2-3-4-5-4-3-2")
mSet<-PlotCorr(mSet, "ptn_11_", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "5-4-3-2-1-2-3-4")
mSet<-PlotCorr(mSet, "ptn_12_", "png", 72, width=NA)
mSet<-PlotCorrHeatMap(mSet, "corr_1_", "png", 102, width=NA, "row", "pearson", "bwm", "overview", F, F, F, 999)

# PCA
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 102, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 102, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)

# PLS-DA
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PLSDA.CV(mSet, "L",4, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 72, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)

# Hierarchical Clustering
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotHeatMap(mSet, "heatmap_0_", "png", 300, width=NA, "norm", "row", "euclidean", "ward.D","bwm", "overview", T, T, NA, T, F)

#Kmeans
mSet<-Kmeans.Anal(mSet, 4)
mSet<-PlotKmeans(mSet, "km_1_", "png", 150, width=NA)

# Random Forest
mSet<-RF.Anal(mSet, 1000,7,1)
mSet<-PlotRF.Classify(mSet, "rf_cls_1_", "png", 72, width=NA)
mSet<-PlotRF.VIP(mSet, "rf_imp_1_", "png", 72, width=NA)
mSet<-PlotRF.Outlier(mSet, "rf_outlier_1_", "png", 72, width=NA)

mSet<-SaveTransformedData(mSet)
```
# Bsub with fewer variables
```{r}
rm(list = ls())
BsubFG <- Bsub.data[-c(1:8, 27:34),]
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/BsubFG")
write.csv(BsubFG,"GLDS138.BsubFG.csv", row.names = F)
library(MetaboAnalystR)

# set up
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "GLDS138.BsubFG.csv", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "NULL", "NULL", "AutoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)

# Anova
mSet<-ANOVA.Anal(mSet, F, 1.0E-9, "fisher", FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 1.0E-9, "tukey", FALSE)
mSet<-PlotANOVA(mSet, "aov_10_", "png", 72, width=NA)

# Correlation analysis
mSet<-PlotCorrHeatMap(mSet, "corr_1_", "png", 102, width=NA, "row", "pearson", "bwm", "overview", F, F, F, 999)

# Pattern Hunter
mSet<-Match.Pattern(mSet, "pearson", "1-2-3-4")
mSet<-PlotCorr(mSet, "ptn_1_", "png", 72, width=NA) 
mSet<-Match.Pattern(mSet, "pearson", "4-3-2-1")
mSet<-PlotCorr(mSet, "ptn_2_", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "1-2-3-2")
mSet<-PlotCorr(mSet, "ptn_3_", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "3-2-1-2")
mSet<-PlotCorr(mSet, "ptn_4_", "png", 72, width=NA)

# PCA
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 102, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 102, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)

# PLS-DA
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PLSDA.CV(mSet, "L",4, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 72, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)

# Hierarchical Clustering
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotHeatMap(mSet, "heatmap_0_", "png", 300, width=NA, "norm", "row", "euclidean", "ward.D","bwm", "overview", T, T, NA, T, F)

#Kmeans
mSet<-Kmeans.Anal(mSet, 4)
mSet<-PlotKmeans(mSet, "km_1_", "png", 150, width=NA)

# Random Forest
mSet<-RF.Anal(mSet, 1000,7,1)
mSet<-PlotRF.Classify(mSet, "rf_cls_1_", "png", 72, width=NA)
mSet<-PlotRF.VIP(mSet, "rf_imp_1_", "png", 72, width=NA)
mSet<-PlotRF.Outlier(mSet, "rf_outlier_1_", "png", 72, width=NA)

mSet<-SaveTransformedData(mSet)
```

# Separate media and pellet
# First try out pellet

```{r}
rm(list = ls())
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/BsubFG")
GLDS138.BsubFGP <- read.csv("GLDS138.BsubFG.csv", check.names = FALSE)
GLDS138.BsubFGP <- GLDS138.BsubFGP[-c(1:18),]
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/BsubFGP")
write.csv(GLDS138.BsubFGP,"GLDS138.BsubFGP.csv", row.names = F)

library(MetaboAnalystR)

# set up
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "GLDS138.BsubFGP.csv", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "NULL", "NULL", "AutoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)

# Anova
mSet<-ANOVA.Anal(mSet, F, 1.0E-3, "fisher", FALSE)
mSet<-PlotANOVA(mSet, "aov_fisher_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 1.0E-3, "tukey", FALSE)
mSet<-PlotANOVA(mSet, "aov_tukey_", "png", 72, width=NA)

# Correlation analysis
mSet<-PlotCorrHeatMap(mSet, "corr_1_", "png", 102, width=NA, "row", "pearson", "bwm", "overview", F, F, F, 999)

# Pattern Hunter
mSet<-Match.Pattern(mSet, "pearson", "1-2-3-4")
mSet<-PlotCorr(mSet, "ptn_1_", "png", 72, width=NA) 
mSet<-Match.Pattern(mSet, "pearson", "4-3-2-1")
mSet<-PlotCorr(mSet, "ptn_2_", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "1-2-3-2")
mSet<-PlotCorr(mSet, "ptn_3_", "png", 72, width=NA)
mSet<-Match.Pattern(mSet, "pearson", "3-2-1-2")
mSet<-PlotCorr(mSet, "ptn_4_", "png", 72, width=NA)

# PCA
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 102, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 102, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)

# PLS-DA
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PLSDA.CV(mSet, "L",4, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 72, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)

# Hierarchical Clustering
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotHeatMap(mSet, "heatmap_0_", "png", 300, width=NA, "norm", "row", "euclidean", "ward.D","bwm", "overview", T, T, NA, T, F)

#Kmeans
mSet<-Kmeans.Anal(mSet, 4)
mSet<-PlotKmeans(mSet, "km_1_", "png", 150, width=NA)

# Random Forest
mSet<-RF.Anal(mSet, 1000,7,1)
mSet<-PlotRF.Classify(mSet, "rf_cls_1_", "png", 72, width=NA)
mSet<-PlotRF.VIP(mSet, "rf_imp_1_", "png", 72, width=NA)
mSet<-PlotRF.Outlier(mSet, "rf_outlier_1_", "png", 72, width=NA)

mSet<-SaveTransformedData(mSet)
```























```{r}
devtools::session_info()
```