---
title: "GLDS-138 with MixOmics"
author: "Yen-Kai Chen"
date: "11/04/2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Load set up
rm(list = ls())
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/mixOmics")
library(mixOmics)

BsubFG <- read.csv("GLDS138.BsubFG.csv", check.names = FALSE, header = TRUE, row.names = 1)

# autoscale function
autoscale <- function(a){
  colmean <- apply(a,2,mean) # column mean
  colsd <- apply(a, 2, sd) # col standard deviation
  cv <- sweep(a, 2, colmean, "-") # minus mean center
  cv <- sweep(cv, 2, colsd, "/") # divide by sd
  return(cv)
}

# Normalise
BsubFG.as <- BsubFG
BsubFG.as[,2:ncol(BsubFG.as)] <- autoscale(BsubFG[,2:ncol(BsubFG)])

X <- BsubFG.as[,2:ncol(BsubFG.as)]
```
```{r}
# Quick Plots
MyResult.pca <- pca(X, ncomp = 3)
plotIndiv(MyResult.pca, group = BsubFG.as$Label, ellipse = TRUE, style = "lattice", legend = TRUE, ind.names = FALSE, comp = c(1,2))
plotVar(MyResult.pca)

# sparse PCA
MyResult.spca <- spca(X, keepX = c(5,5)) # keep top 5 variables of PC1&2
plotIndiv(MyResult.spca, group = BsubFG.as$Label, ellipse = TRUE, style = "ggplot2", legend = TRUE, ind.names = FALSE, comp = c(1,2))
plotVar(MyResult.spca)

# Other PCA
plotIndiv(MyResult.pca, group = BsubFG.as$Label, ellipse = TRUE, style = "3d", legend = TRUE, ind.names = FALSE, 
          title = "Spaceflight vs Ground: Metabolites, PCA comp 1-2-3")
plotVar(MyResult.pca, cutoff = 0.8)
plotVar(MyResult.pca, cutoff =  0.8, style = "3d")
plot(MyResult.pca)
MyResult.pca
plotLoadings(MyResult.pca, ndisplay = 60,
             size.name = rel(0.55))

# Variable selection with sparse PCA
MyResult.spca <- spca(X, ncomp = 3, keepX = c(15, 10, 5)) # top 15, 10, 5 metabolites from PC1, PC2 and PC3
plotIndiv(MyResult.spca, group = BsubFG.as$Label, 
          # pch = as.factor() if a second factor can be used
          legend = TRUE, legend.title = "Treatment", # legend.title.pch = 'if used'
          title = "Spaceflight vs Ground: Metabolites, sPCA comp 1-2",
          ellipse = TRUE)
plotVar(MyResult.spca, cex = 3)  
selectVar(MyResult.spca, comp = 1)$value
plotLoadings(MyResult.spca, comp = 1)
selectVar(MyResult.spca, comp = 2)$value
plotLoadings(MyResult.spca, comp = 2)
tune.pca(X)

```
#Partial Least Squares - Discriminant Analysis
```{r}
# set up
X <- BsubFG.as[,-1]
Y <- BsubFG.as$Label
summary(Y)
dim(X)
length(Y)

# PLS-DA
MyResult.plsda <- plsda(X,Y)
plotIndiv(MyResult.plsda)
plotVar(MyResult.plsda, cutoff = 0.7)

# sPLS-DA
MyResult.splsda <- splsda(X, Y, keepX = c(60,60))
plotIndiv(MyResult.splsda, ind.names = FALSE, legend = TRUE,
          ellipse = TRUE, star = TRUE, title = 'sPLS-DA on BsubFG.as',
          X.label = 'PLS-DA 1', Y.label = 'PLS-DA 2')
plotVar(MyResult.splsda)
selectVar(MyResult.splsda, comp = 1)$name

# Background prediction
background <- background.predict(MyResult.splsda, comp.predicted = 2,
                                 dist = "max.dist")
plotIndiv(MyResult.splsda, comp = 1:2, group = BsubFG.as$Label,
          ind.names = FALSE, title = "Maximum distance",
          legend = TRUE,  background = background)

# ROC - check for ability to predict classification
aud.plsda <- auroc(MyResult.splsda)

# Variable selection output
MyResult.splsda2 <- splsda(X, Y, ncomp = 3, keepX = c(60,40,20))
selectVar(MyResult.splsda, comp = 1)$value
plotLoadings(MyResult.splsda2, contrib = 'max', method = 'mean')
plotIndiv(MyResult.splsda2, style="3d")

# Tuning parameters and numerical outputs
MyResult.plsda2 <- plsda(X,Y, ncomp=10)
set.seed(30) # for reproducbility, otherwise increase nrepeat
MyPerf.plsda <- perf(MyResult.plsda2, validation = "Mfold", folds = 3, 
                  progressBar = FALSE, nrepeat = 10) # Suggest nrepeat = 50, but it then starts to lag

plot(MyPerf.plsda, col = color.mixo(5:7), sd = TRUE, legend.position = "horizontal")
MyPerf.plsda

list.keepX <- c(5:10,  seq(20, 100, 10))
list.keepX

set.seed(30) # for reproducbility, otherwise increase nrepeat
tune.splsda.BsubFG <- tune.splsda(X, Y, ncomp = 2, # suggest to push ncomp a bit more, e.g. 4, this cae, ultimal was 2
                                 validation = 'Mfold',
                                 folds = 3, dist = 'max.dist', progressBar = FALSE,
                                 measure = "BER", test.keepX = list.keepX,
                                 nrepeat = 10)   # we suggest nrepeat = 50

error <- tune.splsda.BsubFG$error.rate
ncomp <- tune.splsda.BsubFG$choice.ncomp$ncomp # optimal number of components based on t-tests on the error rate
ncomp
select.keepX <- tune.splsda.BsubFG$choice.keepX[1:ncomp]  # optimal number of variables to select
select.keepX

plot(tune.splsda.BsubFG, col = color.jet(ncomp))

MyResult.splsda.final <- splsda(X, Y, ncomp = ncomp, keepX = select.keepX)

plotIndiv(MyResult.splsda.final, ind.names = FALSE, legend=TRUE,
          ellipse = TRUE, title="sPLS-DA - final result")
```
# Projection to Latent Structure (PLS)
```{r}
# Set up transcriptomic data
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/mixOmics")
file_url <- "https://genelab-data.ndc.nasa.gov/genelab/static/media/dataset/GLDS-138_rna_seq_Normalized_Counts.csv?version=1"
GLDS138RNA = 'GLDS-138_rna_seq_Normalized_Counts.csv'
download.file(file_url, GLDS138RNA)
edata <- read.csv(GLDS138RNA, stringsAsFactors = FALSE)

dim(edata)
rowName <- edata[,1]
rownames(edata) <- rowName
edata <- edata[,-1]
colnames(edata) <- substr(colnames(edata),start=16,stop=23)
edata <- as.data.frame(edata)
edata <- t(edata)
rowNameE <- rownames(edata)

# set up metabolomic data
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/BsubFGP")
mdata <- read.csv("GLDS138.BsubFGP.csv", check.names = FALSE)
mdata$Sample <- substr(mdata$Sample, start=1, stop = 9)
rowName <- mdata[,1]
rownames(mdata) <- rowName
mdata <- mdata[,-1]
mdata$Label <- substr(mdata$Label, start=8, stop = 14)
mdat <- mdata[,-1]
mdat[,2:ncol(mdat)] <- autoscale(mdata.as[,2:ncol(mdat)]) # normalise
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/mixOmics")

# set up lipidomics data
Ldata <- read.csv("GLDS138.Lipid.as.csv", row.names = 1, check.names = FALSE)
Ldata <- Ldata[c(1:18),]
Ldata <- Ldata[,-c(1:2)]

```
```{r}
#quick start on PLS
X <- edata
Y <- mdat
dim(X); dim(Y)

MyResult.spls <- spls(X, Y, keepX = c(25, 25), keepY = c(10,10))
plotIndiv(MyResult.spls)
plotVar(MyResult.spls, cex = c(3,2.5), legend = TRUE)

plotIndiv(MyResult.spls, group = mdata$Label,
          rep.space = "XY-variate", legend = TRUE,
          legend.title = 'Treatment',
          title = 'Spaceflight Bacillus subtilis: sPLS')

# Clustered image maps
X11()
cim(MyResult.spls, comp = 1)

#Relevance networks
X11()
network(MyResult.spls, comp = 1, cutoff = 0.6, save = 'jpeg',name.save = 'PLS.network')

# Arrow plots
plotArrow(MyResult.spls,group=mdata$Label, legend = TRUE,
          X.label = 'PLS comp 1', Y.label = 'PLS comp 2')
# Short arrows indicate a good agreement found by the PLS between both data sets

# Variable selection outputs
MySelectedVariables <- selectVar(MyResult.spls, comp = 1)
MySelectedVariables$X$name # Selected genes on component 1

MySelectedVariables$Y$name # Selected metabolites on component 1

plotLoadings(MyResult.spls, comp = 1, size.name = rel(0.5))
```
# Multi-block Discriminant Analysis with DIABLO
```{r}
# build on the setup from the PLS
rownames(mdat) <- rowNameE
rownames(Ldata) <- rowNameE
mdata$Label <- as.factor(mdata$Label)
X <- list(RNA = edata,
          metabolite = mdat,
          lipid = Ldata)
Y <- mdata$Label
summary(Y)

list.keepX <- list(RNA = c(10,5), metabolite = c(10,5), lipid = c(10,5))

# quick start
MyResult.diablo <- block.splsda(X, Y, keepX=list.keepX)
plotIndiv(MyResult.diablo,
          ind.names = FALSE,
          legend = TRUE, cex = c(1,2),
          title = "Spaceflight B. subtilis with DIABLO") ## sample plot
plotVar(MyResult.diablo, var.names = c(FALSE, TRUE, FALSE),
        legend = TRUE, pch = c(16, 2, 2))
plotDiablo(MyResult.diablo, ncomp = 1)

circosPlot(MyResult.diablo, cutoff = 0.9, ncol.legend = 1, showIntraLinks = TRUE, line = TRUE, size.variables = 0.6)
cimDiablo(MyResult.diablo, color.blocks = c('darkorchid', 'brown1'), comp = 1, margin=c(8,20), legend.position = "right")
plotLoadings(MyResult.diablo, comp = 2, contrib = "max")

# Relevance network
network(MyResult.diablo, blocks = c(1,2),
        color.node = c('darkorchid', 'brown1'), 
        cutoff = 0.6, save = 'jpeg', name.save = 'DIABLOnetwork')

MyResult.diablo2 <- block.plsda(X, Y) 
```























```{r}
devtools::session_info()
```