---
title: "S. aureus PCA"
author: "Yen-Kai Chen"
date: "22/04/2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# set up
```{r}
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/Saur")

GLDS138.as <- read.csv("GLDS138.as.csv", check.names = FALSE, header = TRUE)
utils::View(GLDS138.as)

# Just S. aureus
Saur.as <- GLDS138.as[c(53:104),]
Saur.as <- Saur.as[,-3]
Saur.as$Label <- gsub("Positive ", "", Saur.as$Label)

# Get rid of Control ASAP and Frozen - so just media and pellet
SaurMP <- Saur.as[-c(19:26, 45:52),]
SaurMP$Label <- factor(SaurMP$Label)

# Just Pellet - the bacteria - comparison of just flight vs ground
SaurFG <- SaurMP[c(19:36),]
SaurFG$Label <- factor(SaurFG$Label)
SaurFG$Label <- gsub("Pellet ", "", SaurFG$Label)

# Just Media consumed by the bacteria - F vs G
SaurMd <- SaurMP[c(1:18),]
SaurMd$Label <- factor(SaurMd$Label)
```
# Start analysis of PCA
```{r}
library(mixOmics)
# the general file
X <- GLDS138.as[,4:ncol(GLDS138.as)]
MyResult.pca <- pca(X, ncomp = 3, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), legend = TRUE, title = 'GLDS138: PCA',
          group = GLDS138.as$Label, legend.title = 'Treatment',
          ellipse = FALSE, style = "ggplot2", ind.names = FALSE, 
          pch = GLDS138.as$species, legend.title.pch = 'Species')
plotVar(MyResult.pca)
plotVar(MyResult.pca, cutoff = 0.8)
MyResult.pca 

# S aureus
X <- Saur.as[,3:ncol(Saur.as)]
MyResult.pca <- pca(X, ncomp = 3, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), legend = TRUE, title = 'S. aureus: PCA',
          group = Saur.as$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.pca, cutoff = 0.8)
MyResult.pca 

# Media and pellet
X <- SaurMP[,3:ncol(SaurMP)]
MyResult.pca <- pca(X, ncomp = 3, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), legend = TRUE, title = 'S. aureus - Media vs Pellet: PCA',
          group = SaurMP$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.pca, cutoff = 0.8)
MyResult.pca 

# Pellet - Flight vs Ground
X <- SaurFG[,3:ncol(SaurFG)]
MyResult.pca <- pca(X, ncomp = 4, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), legend = TRUE, title = 'S. aureus - Flight vs Ground: PCA',
          group = SaurFG$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.pca, cutoff = 0.85)
MyResult.pca 

# Media - Flight vs Ground
X <- SaurMd[,3:ncol(SaurMd)]
MyResult.pca <- pca(X, ncomp = 3, center = TRUE)
plotIndiv(MyResult.pca, comp = c(1,2), legend = TRUE, 
          title = 'S. aureus consumed media - Flight vs Ground: PCA',
          group = SaurMd$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.pca, cutoff = 0.8)
MyResult.pca 
```
# Independent Principal Component Analysis
```{r}
X <- GLDS138.as[,4:ncol(GLDS138.as)]
MyResult.ipca <- ipca(X, ncomp = 3, mode ="deflation")
plotIndiv(MyResult.ipca, comp = c(1,2), legend = TRUE, title = 'GLDS138: IPCA',
          group = GLDS138.as$Label, legend.title = 'Treatment',
          ellipse = FALSE, style = "ggplot2", ind.names = FALSE, 
          pch = GLDS138.as$species, legend.title.pch = 'Species')
plotVar(MyResult.ipca, pch = 20)
plotVar(MyResult.ipca, cutoff = 0.8)
MyResult.ipca$kurtosis 

# S. aureus
X <- Saur.as[,3:ncol(Saur.as)]
MyResult.ipca <- ipca(X, ncomp = 3, mode="deflation")
plotIndiv(MyResult.ipca, comp = c(1,2), legend = TRUE, title = 'S. aureus: IPCA',
          group = Saur.as$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.ipca, cutoff = 0.8)
MyResult.ipca$kurtosis 

# Media and pellet
X <- SaurMP[,3:ncol(SaurMP)]
MyResult.ipca <- ipca(X, ncomp = 3, mode="deflation")
plotIndiv(MyResult.ipca, comp = c(1,2), legend = TRUE, title = 'S. aureus - Media vs Pellet: IPCA',
          group = SaurMP$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.ipca, cutoff = 0.8)
MyResult.ipca$kurtosis
hist(MyResult.ipca$loadings$X[,1], main = "Histogram of IPC1's loadings", xlab = "IPC1 Loadings")
hist(MyResult.ipca$loadings$X[,2], main = "Histogram of IPC2's loadings", xlab = "IPC2 Loadings")
hist(MyResult.ipca$loadings$X[,3], main = "Histogram of IPC3's loadings", xlab = "IPC3 Loadings")

# Pellet - Flight vs Ground
X <- SaurFG[,3:ncol(SaurFG)]
MyResult.ipca <- ipca(X, ncomp = 4, mode="deflation")
plotIndiv(MyResult.ipca, comp = c(1,2), legend = TRUE, title = 'S. aureus - Flight vs Ground: IPCA',
          group = SaurFG$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotIndiv(MyResult.ipca, comp = c(1,2,3), legend = TRUE, title = 'S. aureus - Flight vs Ground: IPCA',
          group = SaurFG$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "3d", ind.names = FALSE)
plotVar(MyResult.ipca, cutoff = 0.8)
MyResult.ipca$kurtosis 
hist(MyResult.ipca$loadings$X[,1], main = "Histogram of IPC1's loadings", xlab = "IPC1 Loadings")
hist(MyResult.ipca$loadings$X[,2], main = "Histogram of IPC2's loadings", xlab = "IPC2 Loadings")
hist(MyResult.ipca$loadings$X[,3], main = "Histogram of IPC3's loadings", xlab = "IPC3 Loadings")

# Media - Flight vs Ground
X <- SaurMd[,3:ncol(SaurMd)]
MyResult.ipca <- ipca(X, ncomp = 3, mode="deflation")
plotIndiv(MyResult.ipca, comp = c(1,2), legend = TRUE, 
          title = 'S. aureus consumed media - Flight vs Ground: IPCA',
          group = SaurMd$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.ipca, cutoff = 0.8)
MyResult.ipca$kurtosis 
```
# sIPCA and others
```{r}
library(mixOmics)
# Media and pellet
X <- SaurMP[,3:ncol(SaurMP)]
MyResult.sipca <- sipca(X, ncomp = 3, mode="deflation", keepX = c(50,50,50))
plotIndiv(MyResult.sipca, comp = c(1,2), legend = TRUE, title = 'S. aureus - Media vs Pellet: sIPCA',
          group = SaurMP$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.sipca, cutoff = 0.8)
MyResult.sipca$kurtosis 

# Pellet - Flight vs Ground
X <- SaurFG[,3:ncol(SaurFG)]
MyResult.sipca <- sipca(X, ncomp = 4, mode="deflation", keepX = c(80,80,80,80))
plotIndiv(MyResult.sipca, comp = c(1,2), legend = TRUE, title = 'S. aureus - Flight vs Ground: sIPCA',
          group = SaurFG$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotIndiv(MyResult.sipca, comp = c(1,2,3), legend = TRUE, title = 'S. aureus - Flight vs Ground: sIPCA',
          group = SaurFG$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "3d", ind.names = FALSE, legend.position = "top")
plotVar(MyResult.sipca, cutoff = 0.8)
MyResult.sipca$kurtosis
plotLoadings(MyResult.sipca)

# Media - Flight vs Ground
X <- SaurMd[,3:ncol(SaurMd)]
MyResult.sipca <- sipca(X, ncomp = 3, mode="deflation", keepX = c(50,50,50))
plotIndiv(MyResult.sipca, comp = c(1,2), legend = TRUE, 
          title = 'S. aureus consumed media - Flight vs Ground: IPCA',
          group = SaurMd$Label, legend.title = 'Treatment',
          ellipse = TRUE, style = "ggplot2", ind.names = FALSE)
plotVar(MyResult.sipca, cutoff = 0.8)
MyResult.sipca$kurtosis 

# top metabolites of PC1
top_10_metab <- names(sort(abs(MyResult.sipca$rotation[,1]), decreasing = TRUE)[1:10])
MyResult.sipca$rotation[top_10_metab,1]

# top metabolites for PC2
top_10_metab <- names(sort(abs(MyResult.sipca$rotation[,2]), decreasing = TRUE)[1:10])
MyResult.sipca$rotation[top_10_metab,2]
```
# Anova
```{r}
anova_data <- SaurFG[,c("Label", "321071", "proline", "pyrophosphate", "urea", "1661", "223535")]
library(tidyverse)
anova_data %>% pivot_longer(-Label, names_to = "Metabolite", values_to = "value") %>%
  mutate(Metabolite = factor(Metabolite, levels = c("melibiose", "321071", "proline", "pyrophosphate", "urea", "1661", "223535"))) %>%
  ggplot(aes(x = Label, y = value, color = Metabolite)) +
  geom_boxplot() +
  facet_wrap(~Metabolite) 

aov.models = anova_data[ , -grep("Label", names(anova_data))] %>%
  map(~ aov(.~ anova_data$Label))
summary(aov.models$`melibiose`)
summary(aov.models$`21709`)
summary(aov.models$`urea`)
summary(aov.models$`maltitol`)
summary(aov.models$`4976`)
summary(aov.models$`glycerol`)
# sIPC1 metabolites is actually incredibly difficult to find differences.
```
#Partial Least Squares - Discriminant Analysis
```{r}
# set up
X <- SaurFG[,-c(1:2)]
Y <- SaurFG$Label
summary(Y)
dim(X)
length(Y)

# PLS-DA
MyResult.plsda <- plsda(X,Y)
plotIndiv(MyResult.plsda, legend = TRUE,
          ellipse = TRUE, star = TRUE, title = 'Spaceflight S. aureus: PLS-DA')
plotVar(MyResult.plsda, cutoff = 0.9)
plotLoadings(MyResult.plsda, comp = 1, title = 'Loadings on comp 1: PLS-DA', 
             contrib = 'max', method = 'mean', ndisplay = 20)

# sPLS-DA
MyResult.splsda <- splsda(X, Y, keepX = c(60,60))
plotIndiv(MyResult.splsda, ind.names = FALSE, legend = TRUE,
          ellipse = TRUE, star = TRUE, title = 'Spaceflight B. subtilis: sPLS-DA',
          X.label = 'PLS-DA 1', Y.label = 'PLS-DA 2')
plotVar(MyResult.splsda, cutoff = 0.85)
selectVar(MyResult.splsda, comp = 1)$name

# Background prediction
background <- background.predict(MyResult.splsda, comp.predicted = 2,
                                 dist = "max.dist")
plotIndiv(MyResult.splsda, comp = 1:2, group = SaurFG$Label,
          ind.names = FALSE, title = "Maximum distance",
          legend = TRUE,  background = background)

##  Tuning parameters and numerical outputs - start from here
# check the best number of components to use 
MyResult.splsda2 <- plsda(X, Y, ncomp = 8)
MyPerf.plsda <- perf(MyResult.splsda2, validation = "Mfold", folds = 3,
                     progressBar = FALSE, nrepeat = 50)
plot(MyPerf.plsda, col = color.mixo(5:7), sd = TRUE, legend.position = "horizontal") # looks to be 2 components

list.keepX <- c(1:10,  seq(20, 100, 10))
list.keepX # output the grid of values tested

tune.splsda.srbct <- tune.splsda(X, Y, ncomp = 2, 
                                 validation = 'Mfold',
                                 folds = 3, dist = 'max.dist', progressBar = FALSE,
                                 measure = "BER", test.keepX = list.keepX,
                                 nrepeat = 50)
error <- tune.splsda.srbct$error.rate
ncomp <- tune.splsda.srbct$choice.ncomp$ncomp # optimal number of components based on t-tests on the error rate
ncomp # confirmed to be 1.
# check the number of metabolites to keep per component
select.keepX <- tune.splsda.srbct$choice.keepX[1:ncomp]  # optimal number of variables to select
select.keepX 
select.keepX <- tune.splsda.srbct$choice.keepX[1:2]  # optimal no of variables for 2 components
select.keepX

plot(tune.splsda.srbct, col = color.jet(2))

# The final graph - we have to use two component 
MyResult.splsda.final <- splsda(X, Y, ncomp = 2, keepX = select.keepX)
plotIndiv(MyResult.splsda.final, ind.names = FALSE, legend=TRUE,
          ellipse = TRUE, title="sPLS-DA - final result")
plotVar(MyResult.splsda.final)
plotLoadings(MyResult.splsda.final, comp = 1, title = 'Loadings on comp 1', 
             contrib = 'max', method = 'mean')

X11()
cim(MyResult.splsda.final, comp = 1, title = "Component 1")
plotArrow(MyResult.splsda.final, legend=T)

# top metabolites of component
top_10_metab <- names(sort(abs(MyResult.splsda.final$mat.c[,1]), decreasing = TRUE)[1:10])
MyResult.splsda.final$mat.c[top_10_metab,1]

# take a look at the boxplot anyway
splsda_metab <- SaurFG[,c("Label", "glycolic acid", "217691", "3-hydroxypropionic acid", "4721", "methionine","glycerol-alpha-phosphate" )]
library(tidyverse)
splsda_metab %>% pivot_longer(-Label, names_to = "Metabolite", values_to = "value") %>%
  mutate(Metabolite = factor(Metabolite, levels = c("glycolic acid", "217691", "3-hydroxypropionic acid", "4721", "methionine","glycerol-alpha-phosphate"))) %>%
  ggplot(aes(x = Label, y = value, color = Metabolite)) +
  geom_boxplot() +
  facet_wrap(~Metabolite)
```
# Convex clustering
```{r}
library(cvxbiclustr)

# create bicluster path
X <- Saur.as[,-c(1:2)] # data matrix to be clustered, rows are features, columns are the samples.
rownames(X) <- Saur.as$Sample
X <- t(X)

# Create annotation for heatmap
types <- Saur.as$Label
ty <- as.numeric(factor(types))
cols <- rainbow(8)
YlGnBu5 <- c('#ffffd9','#c7e9b4','#41b6c4','#225ea8','#081d58')
hmcols <- colorRampPalette(YlGnBu5)(256)

# Construct weights and edge-incidence matrices
phi <- 0.5; k <- 5
wts <- gkn_weights(X,phi=phi,k_row=k,k_col=k)
w_row <- wts$w_row
w_col <- wts$w_col
E_row <- wts$E_row
E_col <- wts$E_col

# Connected Components of Row and Column Graphs
wts$nRowComp
wts$nColComp

## cobra validation
# Initialize path parameters and structures
nGamma <- 7
gammaSeq <- 10**seq(0,1,length.out=nGamma)
# Generate solution path
sol <- cobra_validate(X,E_row,E_col,w_row,w_col,gammaSeq,fraction=0.01)
# Plot validation error
verr <- sol$validation_error
plot(verr)
# Heatmap of data smoothed at the model selected to minimize validation error
ix <- which.min(verr)
groups_row <- sol$groups_row[[ix]]
groups_col <- sol$groups_col[[ix]]
M <- biclust_smooth(X,groups_row,groups_col)
heatmap(M,col=hmcols,labRow=rownames(X),labCol=types,ColSideCol=cols[ty])

heatmap(sol$U[[1]],col=hmcols,labRow=NA,labCol=types,ColSideCol=cols[ty])
heatmap(sol$U[[2]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
heatmap(sol$U[[3]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
heatmap(sol$U[[4]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
heatmap(sol$U[[5]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
```
# clustRviz
```{r}
# set up
library(clustRviz)
GLDS138.as <- read.csv("GLDS138.as.csv", check.names = FALSE, header = TRUE)
# Just S. aureus
Saur.as <- GLDS138.as[c(53:104),]
Saur.as <- Saur.as[,-3]
Saur.as$Label <- gsub("Positive ", "", Saur.as$Label)
Saur.as$Sample <- gsub("SA-", "", Saur.as$Sample)
Saur.as$Sample <- gsub("Med_", "M", Saur.as$Sample)
Saur.as$Sample <- gsub("Pellet_", "P", Saur.as$Sample)
# Get rid of Control ASAP and Frozen - so just media and pellet
SaurMP <- Saur.as[-c(19:26, 45:52),]
SaurMP$Label <- factor(SaurMP$Label)
# Just Pellet - the bacteria - comparison of just flight vs ground
SaurFG <- SaurMP[c(19:36),]
SaurFG$Label <- gsub("Pellet ", "", SaurFG$Label)
SaurFG$Label <- factor(SaurFG$Label)

# Look at the entire thing
X <- Saur.as
rownames(X) <- X$Sample
X <- X[,-c(1:2)]
X <- t(X)

# clustering
carp_fit <- CARP(X, X.center = FALSE)
print(carp_fit)

plot(carp_fit, type = "dendrogram")
plot(carp_fit, type = "dynamic_path") # require virtual machine
plot(carp_fit, type = "js")

# BiClustering
cbass_fit <- CBASS(X) # takes quite long
plot(cbass_fit, heatcol.label.cex = 0.6, heatrow.label.cex = 0.2, k.col = 6) # can't see the long names
plot(cbass_fit, type = "js", k.row = 6) # standard heatmap, seems to have no problems separating the groups appropriately.

# Look at just Pellet Flight vs Ground
X <- SaurFG
rownames(X) <- X$Sample
X <- X[,-c(1:2)]
X <- t(X)

# BiClustering
cbass_fit <- CBASS(X) # takes quite long
plot(cbass_fit, type = "js", k.row = 6)

# boxplot look at the top metabolites
cbass_metab <- SaurFG[,c("Label", "133605", "3122", "4609", "5263", "2-deoxyerythritol", "hydroxycarbamate NIST")]
library(tidyverse)
cbass_metab %>% pivot_longer(-Label, names_to = "Metabolite", values_to = "value") %>%
  mutate(Metabolite = factor(Metabolite, levels = c("133605", "3122", "4609", "5263", "2-deoxyerythritol", "hydroxycarbamate NIST"))) %>%
  ggplot(aes(x = Label, y = value, color = Metabolite)) +
  geom_boxplot() +
  facet_wrap(~Metabolite)



##  move back to this package for just Flight vs Space - actually made it more difficult to see
library(cvxbiclustr)

X <- SaurFG
rownames(X) <- X$Sample
X <- X[,-c(1:2)]
X <- t(X)

# Create annotation for heatmap
types <- SaurFG$Label
ty <- as.numeric(factor(types))
cols <- rainbow(8)
YlGnBu5 <- c('#ffffd9','#c7e9b4','#41b6c4','#225ea8','#081d58')
hmcols <- colorRampPalette(YlGnBu5)(256)

# Construct weights and edge-incidence matrices
phi <- 0.5; k <- 5
wts <- gkn_weights(X,phi=phi,k_row=k,k_col=k)
w_row <- wts$w_row
w_col <- wts$w_col
E_row <- wts$E_row
E_col <- wts$E_col

# Connected Components of Row and Column Graphs
wts$nRowComp
wts$nColComp

## cobra validation
# Initialize path parameters and structures
nGamma <- 7
gammaSeq <- 10**seq(0,1,length.out=nGamma)
# Generate solution path
sol <- cobra_validate(X,E_row,E_col,w_row,w_col,gammaSeq,fraction=0.01)
# Plot validation error
verr <- sol$validation_error
plot(verr)
# Heatmap of data smoothed at the model selected to minimize validation error

heatmap(sol$U[[1]],col=hmcols,labRow=NA,labCol=types,ColSideCol=cols[ty])
heatmap(sol$U[[2]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
heatmap(sol$U[[3]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
heatmap(sol$U[[4]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])
heatmap(sol$U[[5]],col=hmcols,labRow=NA,labCol=NA,ColSideCol=cols[ty])

```
# Setting up Multi-Omics
```{r}
setwd("C:/Users/strki/Documents/Git_R/GLDS-138 metabolomics/GLDS-138-metabolomics/Saur")

# Polar metabolites
GLDS138.as <- read.csv("GLDS138.as.csv", check.names = FALSE, header = TRUE)
# Just S. aureus
Saur.as <- GLDS138.as[c(53:104),]
Saur.as <- Saur.as[,-3]
Saur.as$Label <- gsub("Positive ", "", Saur.as$Label)
Saur.as$Sample <- gsub("SA-", "", Saur.as$Sample)
Saur.as$Sample <- gsub("Med_", "M", Saur.as$Sample)
Saur.as$Sample <- gsub("Pellet_", "P", Saur.as$Sample)
# Get rid of Control ASAP and Frozen - so just media and pellet
SaurMP <- Saur.as[-c(19:26, 45:52),]
SaurMP$Label <- factor(SaurMP$Label)
# Just Pellet - the bacteria - comparison of just flight vs ground
SaurFG <- SaurMP[c(19:36),]
SaurFG$Label <- gsub("Pellet ", "", SaurFG$Label)
SaurFG$Label <- factor(SaurFG$Label)

# set up lipidomics data
Ldata <- read.csv("GLDS138.Lipid.as.csv", row.names = 1, check.names = FALSE)
Ldata <- Ldata[c(37:54),]
Ldata <- Ldata[,-c(1:2)]
L_label <- data.frame(c(rep("Spaceflight", 9), rep("Ground Control", 9)))
Ldata[,"Label"] <- L_label
Ldata <- Ldata[,c("Label", setdiff(names(Ldata), "Label"))]
```
# Projection to Latent Structure (PLS)
```{r}
library(mixOmics)
#quick start on PLS
X <- SaurFG[-c(1:2)]
Y <- Ldata[,-1]
rownames(X) <- SaurFG$Sample
dim(X); dim(Y)

# straight to tuning                    ### virtual machine required for analysis

MyResult.pls <- pls(X,Y, ncomp = 10)
perf.pls <- perf(MyResult.pls, validation = "Mfold", folds = 5,
                  progressBar = FALSE, nrepeat = 50)
plot(perf.pls$Q2.total)
abline(h = 0.0975) # can't even see the line, but you want it to be less than 0.0975

list.keepX <- c(2:10, 15, 20)
# tuning based on MAE                                       # definitely need virtual machine
tune.spls.MAE <- tune.spls(X, Y, ncomp = 4,
                           test.keepX = list.keepX,
                           validation = "Mfold", folds = 5,
                           nrepeat = 50, progressBar = FALSE,
                           measure = 'MAE')
plot(tune.spls.MAE, legend.position = 'topright')
ncomp <- tune.spls.MAE$choice.ncomp$ncomp
ncomp
tune.spls.MAE$choice.keepX # 2, 20, 2, 3, 10, 4, 9, 10, 10, 10

MyResult.spls <- spls(X, Y, keepX = c(2, 20), keepY = c(2,20))
plotIndiv(MyResult.spls, group = SaurFG$Label)
plotVar(MyResult.spls, cex = c(3,3), legend = TRUE)

plotIndiv(MyResult.spls, group = SaurFG$Label,
          rep.space = "XY-variate", legend = TRUE,
          legend.title = 'Treatment',
          title = 'Spaceflight Bacillus subtilis: sPLS')

# Clustered image maps - pointless with 4 metabolites
X11()
cim(MyResult.spls, comp = 1)

#Relevance networks     - pointless with 4 metabolites
network(MyResult.spls, comp = 1, interactive = TRUE, 
        color.edge = color.GreenRed(100))
# network(MyResult.spls, comp = 1, cutoff = 0.89, save = 'jpeg',name.save = 'PLS.network') # if intending to save it

# Arrow plots
plotArrow(MyResult.spls,group=SaurFG$Label, legend = TRUE,
          X.label = 'PLS comp 1', Y.label = 'PLS comp 2')
# Short arrows indicate a good agreement found by the PLS between both data sets
# more useful if we're looking at time related, or soemthing linking from one treatment to another.

# Variable selection outputs
MySelectedVariables <- selectVar(MyResult.spls, comp = 1)
MySelectedVariables$X$name # Selected polar metabolites on component 1

MySelectedVariables$Y$name # Selected non-polar metabolites on component 1

plotLoadings(MyResult.spls, comp = 1, size.name = rel(0.5))

# check both on the boxplot
pls_metab <- SaurFG[,c("Label", "228288", "321071")]
pls_metab[,c("V442", "V453")] <- Ldata[,c("V442", "V453")]
library(tidyverse)
pls_metab %>% pivot_longer(-Label, names_to = "Metabolite", values_to = "value") %>%
  mutate(Metabolite = factor(Metabolite, levels = c("228288", "321071", "V442", "V453"))) %>%
  ggplot(aes(x = Label, y = value, color = Metabolite)) +
  geom_boxplot() +
  facet_wrap(~Metabolite)
```

# Multi-block Discriminant Analysis with DIABLO
```{r}
# Set up
library(mixOmics)
mdat <- SaurFG[-c(1:2)]
Ldat <- Ldata[,-1]
rownames(mdat) <- rownames(Ldat)

X <- list(metabolite = mdat,
          lipid = Ldat)
Y <- SaurFG$Label
summary(Y)

# tune number of components
sgccda.res = block.splsda(X = X, Y = Y, ncomp = 8)

perf.diablo = perf(sgccda.res, validation = 'Mfold', folds = 5, nrepeat = 50)
plot(perf.diablo) 
perf.diablo$choice.ncomp$WeightedVote
ncomp = perf.diablo$choice.ncomp$WeightedVote["Overall.BER", "centroids.dist"]
ncomp

test.keepX = list(metabolite = c(5:9, seq(10, 18, 2), seq(20,30,5)),
                  lipid = c(5:9, seq(10, 18, 2), seq(20,30,5)))

design = matrix(0.1, ncol = length(X), nrow = length(X), 
                dimnames = list(names(X), names(X)))
diag(design) = 0
design 

tune.TCGA = tune.block.splsda(X = X, Y = Y, ncomp = ncomp, 
                              test.keepX = test.keepX, design = design,
                              validation = 'Mfold', folds = 10, nrepeat = 1,
                              cpus = 2, dist = "centroids.dist")
list.keepX = tune.TCGA$choice.keepX
list.keepX # = list(metabolite = c(5,5), lipid = c(18,5)) 
sgccda.res = block.splsda(X = X, Y = Y, ncomp = ncomp, 
                          keepX = list.keepX, design = design)
sgccda.res$design
selectVar(sgccda.res, block = 'metabolite', comp = 1)$metabolite$name
selectVar(sgccda.res, block = 'lipid', comp = 1)$lipid$name

plotDiablo(sgccda.res, ncomp = 1)
plotIndiv(sgccda.res, ind.names = FALSE, legend = TRUE, title = 'DIABLO')
plotArrow(sgccda.res, ind.names = FALSE, legend = TRUE, title = 'DIABLO')

plotVar(sgccda.res, var.names = FALSE, style = 'graphics', legend = TRUE, 
        pch = c(16, 17), cex = c(2,2), col = c('darkorchid', 'brown1'))

circosPlot(sgccda.res, cutoff = 0.92, line = TRUE, 
           color.blocks= c('darkorchid', 'brown1'),
           color.cor = c("chocolate3","grey20"), size.labels = 1.5)

network(sgccda.res, blocks = c(1,2),
        color.node = c('darkorchid', 'lightgreen'), cutoff = 0.7)
network(MyResult.diablo, blocks = c(1,2),
        color.node = c('darkorchid', 'brown1'), 
        interactive = TRUE)

plotLoadings(sgccda.res, comp = 1, contrib = 'max', method = 'median')

# X11()
cimDiablo(sgccda.res, margin=c(9,18), size.legend = 0.9, legend.position = "right",)

perf.diablo = perf(sgccda.res, validation = 'Mfold', M = 3, nrepeat = 50, 
                   dist = 'centroids.dist')
perf.diablo$MajorityVote.error.rate
auc.splsda = auroc(sgccda.res, roc.block = "miRNA", roc.comp = 2)
```


















```{r}
devtools::session_info()
```